### ISSUE TITLE
FastReport.Net 2023.1.8 破解版及逆向思路

### ISSUE THREAD

**Issue by xiaokaixuan** [kaixuan1115/notes#55]
#### 取消打印水印：
**修改：**`FastReport.Print.DefaultPrintController`类中的`PrintPage`方法取消水印代码
![image](https://github.com/kaixuan1115/notes/assets/7234473/6e5a6f59-162f-47e5-b6bd-63621957e5c2)

#### 取消打印页数限制：
**修改：**`FastReport.Print.PageNumbersParser`类的**构造方法**：
![image](https://github.com/kaixuan1115/notes/assets/7234473/61d77fa1-ac27-4ee2-9bab-f745af53aa24)

#### 取消导出水印：
**修改：**`FastReport.Export.ExportBase`类中的`GetOverlayPage`方法, 相关代码
![image](https://github.com/kaixuan1115/notes/assets/7234473/cc6ffc4c-9824-489a-b772-9b6631b0790d)

#### 取消导出页数限制：
**修改：**`FastReport.Export.ExportBase`类中的`Export`方法, 相关代码
![image](https://github.com/kaixuan1115/notes/assets/7234473/953c1c52-05fd-42ae-bf41-b76431871996)

#### 破解版下载
[FastReport.Net_v2023.1.8_Cracked.rar](https://github.com/kaixuan1115/notes/releases/download/assets/FastReport.Net_v2023.1.8_Cracked.rar)
#### 官方版下载
[FRNetDemo_v2023.1.8_Official.rar](https://github.com/kaixuan1115/notes/releases/download/assets/FRNetDemo_v2023.1.8_Official.rar)

**Comment by xiaokaixuan** [comment]
[FastReport完全破解-DLL签名问题.pdf](https://github.com/user-attachments/files/16144830/FastReport.-DLL.pdf)

**Comment by xiaokaixuan** [comment]
> FastReport.Net 简单表格数据源
```xml
<Dictionary>
    <TableDataSource Name="Customers" ReferenceName="NorthWind.Customers" DataType="System.Int32" Enabled="true">
      <Column Name="CustomerID" DataType="System.String"/>
      <Column Name="CompanyName" DataType="System.String"/>
      <Column Name="Address" DataType="System.String"/>
      <Column Name="City" DataType="System.String"/>
    </TableDataSource>
</Dictionary>
```

**Comment by xiaokaixuan** [comment]
> **快速上手使用 `FastReport.NET` 示例**
```c#
private void button1_Click(object sender, EventArgs e)
{
    const string FORM_TEXT = "测试报表";
    FastReport.Utils.Config.PreviewSettings.Buttons = 
        PreviewButtons.Save | PreviewButtons.Print | PreviewButtons.Close | PreviewButtons.Watermark;
    FastReport.Utils.Config.PreviewSettings.Text = $"{FORM_TEXT} -- 打印预览";
    Report report = new FastReport.Report();
    report.Load(".\\TestReport.frx");
    report.RegisterData(lvDays, "datasource"); // List<GV_DayStat> lvDays = new List<GV_DayStat>();
    var textObject = report.FindObject("Title") as TextObject;
    if (textObject != null) textObject.Text = FORM_TEXT;
    textObject = report.FindObject("SubTitle") as TextObject;
    if (textObject != null) textObject.Text = "( 2024-07-01 12:33:11 至 2024-07-08 12:40:30 )";
    report.Preview = previewControl1; // 预览控件显示
    report.Preview.Buttons = PreviewButtons.Save | PreviewButtons.Print | PreviewButtons.Close | PreviewButtons.Watermark;
    report.Prepare();
    // report.Design(); // 此语句可自动关联List内对象属性到数据源 调试编辑好报表后再注释掉
    report.ShowPrepared();
}
```

**Comment by ahdung** [comment]
这个不能用于.net core吧，dll全是framework的
